### ISSUE TITLE
Local time for daylight savings is wrong

### ISSUE THREAD

**Issue by physixtential** [Kreisverkehr/discord-event-bot#56]
Create and even with 6pm GMT-8
Set local time on your computer to pacific time (gmt-8). Local time on the event will appear as 7pm. That is not correct. Pacific is currently on daylight time. This means that GMT-8 should actually be 7 hours behind GMT, but still read as GMT-8. 

![image](https://user-images.githubusercontent.com/55558141/134725153-e4337cd7-f5eb-4f67-9988-770ce591d7b8.png)

**Comment by Kreisverkehr** [comment]
Hi,
Timezone handeling is currently unsupported. The bot will save all times in it's local timezone setting.
May I ask how you took that screenshot? It does not seem familliar to me. Did you make any modifications to my code?

**Comment by physixtential** [comment]
shoot... I must have found the wrong github. I guess there must be another
discord wow event handler if that screenshot doesnt look familiar. You can
close my issue.
