### ISSUE TITLE
Need help to create an event

### ISSUE THREAD

**Issue by Azurz** [Kreisverkehr/discord-event-bot#62]
Hi, can you give me an example for the create an event command?

thank you

**Comment by Kreisverkehr** [comment]
Hi Azurz,
sorry for the late reply. In case you haven't figured out yet: This is pretty simple.
To start the command mention the bot. Be carefull, this is case sensitive. The keywords to create an event are `event create` followed by you events data. for example:
`@EventBot create event "Azurz sample event" "2021-11-15 16:46" 1H30M`

The formatting of the date and time values heavily depends on the culture settings of the mashine your bot runs on.

you can get a more detailed help message by typing `@EventBot help event create`
